name: mobile
description: Mobile first To-Do Tracker you waited for!

publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  collection: ^1.16.0
  intl: ^0.18.0
  path: ^1.8.2
  path_provider: ^2.0.11
  get_it: ^7.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  go_router: ^6.0.3
  #  TODO watch for fixed version https://github.com/flutter/flutter/issues/89578
  #  camera: ^0.10.3
  camera:
    git:
      url: https://github.com/flutter/plugins
      path: packages/camera/camera
      ref: 9e46048ad2e1f085c1e8f6c77391fa52025e681f
  riverpod_annotation: ^1.1.1
  shared_preferences: ^2.0.17
  flutter_launcher_icons: ^0.11.0
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.2.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1
  custom_lint: ^0.2.12
  riverpod_lint: ^1.0.1

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/logo/icon.jpg"
  android: true
  ios: true
  min_sdk_android: 21
